@startuml Database

title "Database Mockup"

hide methods

' classes
class User {
    /'
    PK - userId
    '/

    userId
    username
    password
    name
    DOB
    email
    NIF
    isAdmin
}

class Freelancer {
    /'
    PK - freelancerId
    '/

    freelancerId
}

class Client {
    /'
    PK - clientId
    '/

    clientId
}

class Pet {
    /'
    PK - petId
    FK - owner, aponta para Client
    '/

    petId
    name
    DOB
    ownerId
}

class Service {
    /'
    PK - serviceId
    '/

    serviceId
    name
}

class Ads {

}

class Animal {
    /'
    PK - animalId
    '/

    animalId
    type
}

class Animal_types {
    
}

class Ad_animals {

}

class Review {

}

class Orders {

}


' associations

' inheritance
User <|-- Freelancer
User <|-- Client

Client "1" -- "many" Pet : owns >

Animal "many" -- "1" Pet

Service "many" -- "many" Freelancer : does <
Service "many" -- "many" Client : hire >


@enduml
